fixes

diff --git a/dvtm-status b/dvtm-status
--- a/dvtm-status
+++ b/dvtm-status
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 DVTM_PIPE_BASEDIR="/tmp/dvtm.$$"
 export DVTM_STATUS_FIFO="$DVTM_PIPE_BASEDIR/status"
@@ -7,8 +7,8 @@ export DVTM_CMD_FIFO="$DVTM_PIPE_BASEDIR/cmd"
 mkdir -p "$DVTM_PIPE_BASEDIR"
 [ -p "$DVTM_STATUS_FIFO" ] || mkfifo -m 600 "$DVTM_STATUS_FIFO" || \
     { echo "Cannot create status pipe"; exit 1; }
-[ -p "$DVTM_CMD_FIFO" ]    || mkfifo -m 600 "$DVTM_CMD_FIFO"    || \
-    { echo "Cannot create command pipe"; exit 1; }
+# [ -p "$DVTM_CMD_FIFO" ]    || mkfifo -m 600 "$DVTM_CMD_FIFO"    || \
+#     { echo "Cannot create command pipe"; exit 1; }
 
 while true; do
 	date +%H:%M
@@ -16,7 +16,8 @@ while true; do
 done > "$DVTM_STATUS_FIFO" &
 
 STATUS_PID=$!
-dvtm -s "$DVTM_STATUS_FIFO" -c "$DVTM_CMD_FIFO" "$@" 2> /dev/null
+echo "$STATUS_PID"
+dvtm -s "$DVTM_STATUS_FIFO" # -c "$DVTM_CMD_FIFO" "$@" # 2> /dev/null
 kill $STATUS_PID
 wait $STATUS_PID 2> /dev/null
 rm -f "$DVTM_STATUS_FIFO" "$DVTM_CMD_FIFO"
